### ISSUE TITLE
[BUG] - -Confirm flash ignored on Set-DokuPageData

### ISSUE THREAD

**Issue by asmith3006** [AndyDLP/PSDokuWiki#26]
**Describe the bug**
When using Set-DokuPageData I wish to bypass the confirmation as this is being used in an automation system. Adding -Confirm does not take expected effect of bypassing the prompt.

**To Reproduce**
1. Connect to a session
2. run command ``Set-DokuPageData -FullName "ns:ns:ns:page" -RawWikiText "some new values" -Confirm"
3. Press Enter

**Expected behavior**
Command should run without further input

**Machine Info(please complete the following information):**
 - OS: Windows 10
 - PS Version 7.0.2

**Comment by AndyDLP** [comment]
Hi @asmith3006 ,

Going on the assumption that you didn't make a typo in your command, when using the -Confirm parameter you need to append :$false to the end for it to work as you expect e.g.
`Set-DokuPageData -FullName "ns:page" -RawWikiText "new text" -Confirm:$false`

Otherwise you are explicitly asking it to confirm every step.

Assuming you did & so were already specifying -Confirm:$false, I'm having trouble reproducing if I'm being honest (same OS and PS version). Would you please provide some more context ?

Cheers,
Andy

**Comment by asmith3006** [comment]
Andy, no, I didn't make a typo. You're absolutely right, sorry. 

Adding -Confirm:$false does the trick. 

Thanks for the amazing work.
