### ISSUE TITLE
[FEATURE] - add page with HTML

### ISSUE THREAD

**Issue by ludovicbernard** [AndyDLP/PSDokuWiki#33]
Hello ,
is it possible to add a page with an html file
thank you

**Comment by AndyDLP** [comment]
I don't think this is possible with pure PowerShell, although from some googling it appears that you can convert HTML to DokuWiki markup with [Pandoc](https://pandoc.org/). I suppose you could then write a wrapper script around Pandoc and/or just `Get-Content` the outputted files and then use `Set-DokuPageData`.

Closing this as an issue since doing the above in this module is not the best place.
