### ISSUE TITLE
[FEATURE] - Add PS 7 compatibility

### ISSUE THREAD

**Issue by AndyDLP** [AndyDLP/PSDokuWiki#9]
Add PS 6.0+ compatibility

**Comment by c-0815** [comment]
I'm also interested in this feature, as I want to use your module in CentOS Linux. Are you already developing on this?

regards

Ralph

**Comment by AndyDLP** [comment]
I haven't been specifically developing for Linux so far I'm afraid, this item was a bit of nice-to-have for me since I don't use Linux on a day to day basis. That said, what happens if you try and import it anyway?

*You're also more than welcome to contribute if you fancy it :)

**Comment by c-0815** [comment]
after the successful module import the call of any cmdlet returns that
this cmdlet is unknown.

Freundliche Grüße

Ralph Engler

SB Anwendungsbetreuung
 


>>> AndyDLP <notifications@github.com> 29.08.2020 17:16 >>>
I haven't been specifically developing for Linux so far I'm afraid,
this item was a bit of nice-to-have for me since I don't use Linux on a
day to day basis. That said, what happens if you try and import it
anyway?
*You're also more than welcome to contribute if you fancy it :)
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
(
https://github.com/AndyDLP/PSDokuWiki/issues/9#issuecomment-683303805) ,
or unsubscribe
(
